# Generated by Django 4.2.29 on 2026-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(db_index=True, max_length=50)),
                ('activity_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('start_date', models.DateTimeField()),
                ('distance', models.FloatField(default=0)),
                ('moving_time', models.IntegerField(default=0)),
                ('elapsed_time', models.IntegerField(default=0)),
                ('average_speed', models.FloatField(default=0)),
                ('max_speed', models.FloatField(default=0)),
                ('total_elevation_gain', models.FloatField(default=0)),
                ('elev_high', models.FloatField(blank=True, null=True)),
                ('elev_low', models.FloatField(blank=True, null=True)),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_state', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('achievement_count', models.IntegerField(default=0)),
                ('kudos_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('pr_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
