# Generated by Django 4.2.29 on 2026-03-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='best_efforts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='gear_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='individual_activity_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='laps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='map_polyline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='primary_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='segment_efforts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
