# Generated by Django 4.2.29 on 2026-03-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_best_efforts_activity_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(max_length=50, unique=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('default_sport', models.CharField(default='Run', max_length=50)),
                ('default_format', models.CharField(default='speedDesc', max_length=50)),
                ('default_date', models.CharField(default='allTime', max_length=50)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
